# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-lint" do
  version "0.1.7"

  on_macos do
    on_arm do
      sha256 "6dd998eb36a3c7d6969510a7846ac7450fa64635387b287bd0d87ff51a849e98"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "417404281b5be2f06098720a62e4df50006b83100ab7de26fa20b9256003ce30"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8effb54ac8413629f50b965dc3888df2e239dd393b48083c4171d9962ea44b0f"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce70bfa4b69e7ab6e8a9fc37a1df49a43ea1bba31e5b1f2b0a9ec3668dfe3142"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "harness-lint"
  desc "Local context hygiene and usage analyzer for coding agent harnesses"
  homepage "https://github.com/kespineira/harness-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-lint"

  # No zap stanza required

  caveats <<~EOS
    This cask is not signed or notarized; review the release before running it.
  EOS
end
