# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-lint" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "5d792dcc855a44b2e086a09d1326dd6366085d58dafd5199ddef7f3abdf83674"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "00ae786c34f8e5ab22b68a4227493323fab10c9c844d90e3d71fd50538bdbbf5"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa7aaa8d1bf6ec1cda099070dd1435d43b148e10b05862c96ca1a66fb316c5a5"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f571d349fda221a8235c4c3e57f7d7c1524a5fd23239fab9e528fcfc0a2944fe"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "harness-lint"
  desc "Local context hygiene and usage analyzer for coding agent harnesses"
  homepage "https://github.com/kespineira/harness-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-lint"

  # No zap stanza required

  caveats <<~EOS
    This cask is not signed or notarized; review the release before running it.
  EOS
end
