# This file was generated by GoReleaser. DO NOT EDIT.
cask "harness-lint" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "0b95bb5f9e1b7f032e5a83e51ca91bdc24b6f00de03ad7b4acf6a35efa0d5fbe"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "14e5cfe6a2a7330b4c8ff816d858ac0abf5cb77162a1a908f08c921b3deba786"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3cc21c57c6d7b0000d8254c18b7e7ccd4733f623fa09fe4a62f2b58d6c2bd377"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8a76951a5aa7b6cd45720066a578e3076f74e758d64ac3d626354b77018f4c81"
      url "https://github.com/kespineira/harness-lint/releases/download/v#{version}/harness-lint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "harness-lint"
  desc "Local context hygiene and usage analyzer for coding agent harnesses"
  homepage "https://github.com/kespineira/harness-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "harness-lint"

  # No zap stanza required

  caveats <<~EOS
    This cask is not signed or notarized; review the release before running it.
  EOS
end
